### PR TITLE
Improved Documentation

### PR DESCRIPTION
**Pull request by papercheck**
Hi, John,

Per our previous discussion, here is the revised documentation. It is now on the `gh-pages` branch. Please let me know if you have any questions.

Have a productive day!

-Darren

### CODE REVIEW

**Comment by johnbintz** [comment]
Actually, I would want you to integrate whatever new information you want to relay to end users in the `index.md` file at the root of `gh-pages`, which would mainly be about the Xvfb stuff, Qt, and RubyMine. That information would then become part of the main documentation at http://johnbintz.github.com/jasmine-headless-webkit/. That way, all the information is in one place.

**Comment by papercheck** [comment]
I see, sorry, I didn't realize that. I will go ahead and make that change.

-Darren

**Comment by johnbintz** [comment]
And since it's a GitHub Pages site, use Jekyll to preview your edits: `jekyll --server` should do it.

**Comment by papercheck** [comment]
Awesome,

I have been meaning to get around to using Jekyll. This is a good excuse 
to do it.

-Darren

**Comment by johnbintz** [comment]
Hey, not only did I merge in your docs, but I added basic Qt detection capabilities to the latest HEAD for when the runner gets compiled. Want to take a look at it and give me your opinion?

**Comment by papercheck** [comment]
Hi, John,

 I have been out of the office for a couple of weeks and just saw this  email. The documentation looks great; I have not had a chance to re-run  the Jasmine Headless Webkit gem. I think I have another laptop with  Ubuntu on it, and I can try to install the gem as I know it does not  have Qt installed.

 -Darren

-----Original Message-----

**Comment by papercheck** [comment]
Hi, John,

I have been out of the office for a couple of weeks and just saw this 
email. The documentation looks great; I have not had a chance to re-run 
the Jasmine Headless Webkit gem. I think I have another laptop with 
Ubuntu on it, and I can try to install the gem as I know it does not 
have Qt installed.

-Darren

**Pull request merged**
