### PR TITLE
Add support for haml_coffee_assets

### PR DESCRIPTION
**Pull request by joshed-io**
I am a big fan of JHW and I am warming up to haml-coffee, but they don't work together out of box. So, I created a JHW fork and got the two gems to play nicely together. I did a quick write up about it here - http://blog.joshdzielak.com/blog/2011/12/24/using-haml-coffee-assets-with-jasmine-headless-webkit/. (Please do let me know if I any incorrect statements/assumptions about JHW in the post.)

The fork works, and the impact to the developer isn't severe - just getting their haml coffee assets config externalized so both JHW and Rails can see it. 

But the fork does add a little heft to files_list.rb. There's probably a better way to get that in there but I figured it better to get your thoughts first. And I wanted to see if this support was something you wanted to bring in generally and if so how you would structure it. Thanks.

### CODE REVIEW

**Comment by johnbintz** [comment]
Thanks for the patch! I've been thinking about how to handle this best and, since there are going to be a bunch of other gems that may need special handling, I'm going to move to a plugin-ish system where the libraries that JHW can potentially include will be defined as files in a directory in the tree. If the file has any code, it'll be treated as initialization for that library. I'm working on getting reporters all broken out, and then will be fixing issues with Qt 4.8.0. Once that's done, I'll get what you've done merged in to this new setup.

**Comment by joshed-io** [comment]
You're welcome, thanks for this awesome library. Plugin approach sounds solid, let me know if I can be of any help.

**Comment by johnbintz** [comment]
Take a look at #111. That's going to be the recommended way to do this.

**Comment by joshed-io** [comment]
Cool, thanks. I'll see if I can get haml coffee templates to work using that method sometime in the next week or so.

**Comment by joshed-io** [comment]
Ok - I actually threw together a full example app of JHW and HCA working together that uses the new pattern. 

https://github.com/dzello/headless_hamlc

It's not perfect but it gets the job done for now. If I had a cleaner way to hook into the asset paths that files_list.rb I could probably clean it up more (you can see the implementation in spec/javascripts/helpers/spec_helper.rb)

**Pull request closed without merging**
